{{- if .Values.storageclass.createBuiltIn }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pure
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageclass.isPureDefault }}"
  labels:
    kubernetes.io/cluster-service: "true"
{{ include "pure_csi.labels" . | indent 4}}
provisioner: pure-csi # This must match the name of the CSIDriver. And the name of the CSI plugin from the RPC 'GetPluginInfo'
parameters:
  backend: {{ .Values.storageclass.pureBackend | default "block" | quote }}
  csi.storage.k8s.io/fstype: {{ .Values.flasharray.defaultFSType | default "xfs" | quote }}
  createoptions: {{ .Values.flasharray.defaultFSOpt | default "-q" | quote }}

{{- if .Values.flasharray.defaultMountOpt }}
mountOptions:
  {{- range .Values.flasharray.defaultMountOpt }}
  - {{ . }}
  {{- end }}
{{- end }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-file
  labels:
    kubernetes.io/cluster-service: "true"
{{ include "pure_csi.labels" . | indent 4}}
provisioner: pure-csi # This must match the name of the CSIDriver. And the name of the CSI plugin from the RPC 'GetPluginInfo'
parameters:
    backend: file
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-block
  labels:
    kubernetes.io/cluster-service: "true"
{{ include "pure_csi.labels" . | indent 4}}
provisioner: pure-csi # This must match the name of the CSIDriver. And the name of the CSI plugin from the RPC 'GetPluginInfo'
parameters:
  backend: block
  csi.storage.k8s.io/fstype: xfs
  createoptions: -q

{{- if .Values.flasharray.defaultMountOpt }}
mountOptions:
  {{- range .Values.flasharray.defaultMountOpt }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
